### PR TITLE
Split into core and server-side packages

### LINKED ISSUE #18: break the main Servant.Checked.Exceptions module up into a couple different modules
* Servant.Checked.Exceptions.Verbs -- this should contain the VerbWithErr stuff
* Servant.Checked.Exceptions.Envelope -- this should contain the Envelope stuff

These two modules should be re-exported from Servant.Checked.Exceptions.

### LINKED ISSUE #25: Break into combinator/backend packages
We use `servant-checked-exceptions` in the frontend, and would like to avoid a transitive dependency on `servant-server`, `servant-client`, `conduit` etc.

What do you think of having two packages here `servant-checked-exceptions-core` (just types and pure functions) and `servant-checked-exceptions` (instances and functions that depend on server-side code)?

### PR DESCRIPTION
**Pull request by imalsogreg**
Closes #25 and closes #18

Tasks:
 - [X] Partition modules into "core" (potentially usable in a browser) and "server-side" packages
 - [X] Separate modules in "core" for `Envelope` and `Verbs`
 - [X] Maintain the `Internal/` style
 - [X] Ensure `servant-checked-exceptions-core` compiles under ghc and ghcjs
 - [X] Ensure `servant-checked-exceptions` tests pass under ghc
 - [X] Fix up inline documentation (haddocks are in the appropriate modules)
 - [x] Fix `stack.yaml` file
 - [X] Squash commits, clean up PR

### CODE REVIEW

**Comment by imalsogreg** [comment]
@cdepillabout Where to put your great haddock tutorial?

It is semantically closer to `servant-checked-exceptions-core`.

But maybe we want it to be available on this package's _normal_ entry point: `servant-checked-exceptions`.

Or we could put it in both packages, but that's code duplication.

**Comment by cdepillabout** [comment]
@imalsogreg Thanks for doing the work on this, it looks good!

Are you using this professionally (or at least in a relatively serious personal project)?  If so, would you want to be a maintainer for servant-checked-exceptions?  On the off chance that something happened to me, it would be nice to have someone else that has push access to this repository and access to hackage.

Are you using `stack`?  I've kinda slacked off with keeping this in stackage, but if you're actively using stackage I'll be sure to get it back in after doing a new release.

> Where to put your great haddock tutorial?  It is semantically closer to servant-checked-exceptions-core.

I don't really have a strong opinion on this.  However, it would be nice to add a link to it on relevant pages.  For instance, if you add it to servant-checked-exceptions-core but not to servant-checked-exceptions, it would be nice to add a link to it on the servant-checked-exceptions page.

**Comment by cdepillabout** [comment]
It looks like some of the travis builds are failing because of missing files.  Here's an idea of what we can do for the `README.md`, `CHANGELOG.md` and `stack.yaml`.

- `README.md`: Maybe we could just sym link the `README.md` to `servant-checked-exceptions/README.md` and `servant-checked-exceptions-core/README.md`.  That way there would only be one README that would need to be kept up to date.

- `CHANGELOG.md`: I think it would be nice to keep an up-to-date `CHANGELOG.md` for each of `servant-checked-exceptions` and `servant-checked-exceptions-core`.  Could you add changelog entries for the changes you have made in this PR?  Linking back to this PR and the issues #25 and #18 would be great.  We can make a major version bump for the next version, so it could be v2.0.0.0.

- `stack.yaml`:  You can probably just take this out of the `*.cabal` files.

**Comment by imalsogreg** [comment]
@cdepillabout Cool, I'd be more than happy to co-maintain. We use this library in production at FormationAI (formerly known as Takt).

I don't know much about stack/stackage in practice. So while I'm happy to try to keep stack.yaml files up to date, getting that right is something that I may lean on travis for than getting right on my own :)

Adopted your ideas for `README.md`, `CHANGELOG.md` and `stack.yaml` - CI looking better, still working through errors.

**Comment by cdepillabout** [comment]
I fixed up the errors that were occurring on Travis.  I'm not sure what was causing them.  All I did was update the `.travis.yml` file with the latest version linked from [here](https://docs.haskellstack.org/en/stable/travis_ci/).

> I don't know much about stack/stackage in practice. So while I'm happy to try to keep stack.yaml files up to date, getting that right is something that I may lean on travis for than getting right on my own

Okay, that's no problem.  I'll keep the `stack.yaml` files updated :+1: 

> I'd be more than happy to co-maintain.

Okay great.  I've invited you as a collaborator for this repo.  I think Github should send you an email with more information.


I think this should be about ready for release?  Feel free to merge this in when you feel it is ready.  I'll do the initial release of servant-checked-exceptions-core and then also release servant-checked-exceptions.  I'll then add you as a maintainer on Hackage.  Let me know what you hackage username is.

**Comment by imalsogreg** [comment]
@cdepillabout Great. Thanks for the fix! Sounds like a plan. I'm `imalsogreg` on hackage.

**Comment by cdepillabout** [comment]
Thanks! This has been released as the following packages:

https://hackage.haskell.org/package/servant-checked-exceptions-core-2.0.0.0
https://hackage.haskell.org/package/servant-checked-exceptions-2.0.0.0

You've also been added as a maintainer for those two packages!

**Pull request merged**
